projek/mobils/urls.py
from . import views
from django.urls import path

app_name = 'mobils'

urlpatterns = [
    path("", views.index, name='index'),
]

projek/project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('superuser/', admin.site.urls),
    path("", views.welcome),
    path('mobils/', include('mobils.urls', namespace='mobils')),
    path('readcsv/', include('readcsv.urls', namespace='readcsv')),
    path('readjson/', include('readjson.urls', namespace='readjson')),
    path('readxml/', include('readxml.urls', namespace='readxml'))

    

]




projek/readcsv/urls.py
from . import views
from django.urls import path

# this apps create by TANPAGULA grup

app_name = 'readcsv'

urlpatterns = [
    path("", views.index, name='index'),
]

projek/readjson/urls.py
from . import views
from django.urls import path

app_name = 'readjson'

urlpatterns = [
    path("", views.index, name='index'),
]

projek/readxml/urls.py
from . import views
from django.urls import path

app_name = 'readxml'

urlpatterns = [
    path("", views.index, name='index'),
]

projek/mobils/models.py
from django.db import models

# Create your models here.
class Mobil(models.Model):
	brand = models.CharField(max_length=150)
	model = models.CharField(max_length=150)
	price = models.IntegerField()

	def __str__(self):
		return self.brand

projek/readcsv/models.py
from django.db import models

# Create your models here.
# this apps create by TANPAGULA grup

projek/readjson/models.py
from django.db import models

# Create your models here.

projek/readxml/models.py
from django.db import models

# Create your models here.

projek/mobils/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Mobil

# Create your views here.
def index(request):
	mobils = Mobil.objects.all()
	return render(request, 'mobils/index.html', {'mobils': mobils})


	# output = ', '.join(str(mobil) for mobil in mobils)
	# return HttpResponse(output)

projek/project/views.py
from django.shortcuts import render

def welcome(request):
		return render(request, 'welcome.html')

projek/readcsv/views.py
from django.shortcuts import render
from .rcsv import *


# Create your views here.
# rows = []

# this apps create by tanpagula grup

# file = with open('Cars.csv','r') as csvfile:
# this apps create by TANPAGULA grup
# 	csvreader = csv.reader('csvfile')
# 	rows = list(csvreader)

def index(request):
	return render(request, 'index.html', {'rows':rows})

projek/readjson/views.py
from django.shortcuts import render
from .rjson import *


# Create your views here.

def index(request):
	return render(request, 'index.html', {'rows':datas})

projek/readxml/views.py
from django.shortcuts import render
from .rxml import *


# Create your views here.

def index(request):
	return render(request, 'index.html',)

projek/mobils/templates/mobils/index.html
{% extends 'base.html' %}

{% block title %}
Halaman Mobil
{% endblock %}

{% block content %}
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Brand</th>
				<th scope="col">Model</th>
				<th scope="col">Price</th>
			</tr>
		</thead>
		<tbody>
			{% for mobil in mobils %}
				<tr>
					<th scope="row">{{mobil.id}}</th>
					<td>{{mobil.brand}}</td>
					<td>{{mobil.model}}</td>
					<td>{{mobil.price}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

projek/readcsv/templates/index.html
{% extends 'base.html' %}

{% block title %}
Halaman ReadCSV
{% endblock %}

{% block content %}
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Name</th>
				<th scope="col">Price</th>
			</tr>
		</thead>
		<tbody>
			{% for row in rows %}
				<tr>
					<th scope="row">{{row.Id}}</th>
					<td>{{row.Name}}</td>
					<td>{{row.Price}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

projek/readjson/templates/index.html
{% extends 'base.html' %}

{% block title %}
Halaman ReadJson
{% endblock %}

{% block content %}
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Name</th>
				<th scope="col">Price</th>
			</tr>
		</thead>
		<tbody>
			{% for row in rows %}
				<tr>
					<th scope="row">{{row.Id}}</th>
					<td>{{row.Name}}</td>
					<td>{{row.Price}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

projek/readxml/templates/index.html
{% extends 'base.html' %}

{% block title %}
Halaman ReadJson
{% endblock %}

{% block content %}
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Name</th>
				<th scope="col">Price</th>
			</tr>
		</thead>
		<tbody>
			{% for row in rows %}
				<tr>
					<th scope="row">{{row.Id}}</th>
					<td>{{row.Name}}</td>
					<td>{{row.Price}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

projek/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap');
	.nav-item .nav-link{
		font-family: 'Roboto Mono', monospace !important;
				color: blue !important;
	}
	</style>
	<title>{% block title %} {% endblock %}</title>
</head>
<body>
	<main>
		<div class="bg-dark">
			<nav class="navbar navbar-dark container">
				<div class="">
					<a class="navbar-brand" href="#" style="font-family: 'Times New Roman', monospace;">PIRAMIDA</a>
				</div>
				<ul class="Times New Roman justify-content-end">
					<li class="Times New Roman">
						<a href="/" class="Times New Roman-link text-blue">Home</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'mobils:index' %}" class="Times New Roman-link text-blue">Jenis Mobil</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'readcsv:index' %}" class="Times New Roman-link text-blue">JenisMobil.CSV</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'readxml:index' %}" class="Times New Roman-link text-blue">JenisMobil.XML</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'readjson:index' %}" class="Times New Roman-link text-blue">JenisMobil.JSON</a>
					</li>					
				</ul>
			</nav>
		</div>
		{% block content %}

		{% endblock %}

	</main>
	<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

projek/templates/welcome.html
{% extends 'base.html' %}

{% block title%}
Landing Page
{% endblock %}

{% block content %}
	<div class="container">
		<div class="times new roman">
			
			<div>
				<label>Kelompok</label>
			</div>
			<div>
				
				<ol type="A">
					<li>Nama Kelompok :
						<ul type="none">
							<li color="blue">PIRAMIDA</li>
						</ul>
					</li>
					<li>Anggota Kelompok :
						<ul type="none">
							<li> 191080200138 - Dewi Rohmadiniyah</li>
							<li> 191080200154 - Della Swastika Nur Aini</li>
							<li> 191080200251 - Yenni Seftiardiyah</li>
						</ul>
					</li>
					<li>
						Framework Pilihan :
						<ul type="none">
							<li>Python Django (2)</li>
						</ul>
					</li>
				</ol>
			</div>
		</div>
	</div>
{% endblock %}